aws s3 cp Alameda s3://snugabug/images/Alameda --recursive
aws s3 cp Alamo s3://snugabug/images/Alamo --recursive
aws s3 cp Albany s3://snugabug/images/Albany --recursive
aws s3 cp AmericanCanyon s3://snugabug/images/AmericanCanyon --recursive
aws s3 cp Antioch s3://snugabug/images/Antioch --recursive
aws s3 cp Aptos s3://snugabug/images/Aptos --recursive
aws s3 cp Atherton s3://snugabug/images/Atherton --recursive
aws s3 cp AvilaBeach s3://snugabug/images/AvilaBeach --recursive
aws s3 cp Belmont s3://snugabug/images/Belmont --recursive
aws s3 cp BenLomond s3://snugabug/images/BenLomond --recursive
aws s3 cp Benicia s3://snugabug/images/Benicia --recursive
aws s3 cp Berkeley s3://snugabug/images/Berkeley --recursive
aws s3 cp BoulderCreek s3://snugabug/images/BoulderCreek --recursive
aws s3 cp Brentwood s3://snugabug/images/Brentwood --recursive
aws s3 cp Brisbane s3://snugabug/images/Brisbane --recursive
aws s3 cp Burlingame s3://snugabug/images/Burlingame --recursive
aws s3 cp Calistoga s3://snugabug/images/Calistoga --recursive
aws s3 cp Campbell s3://snugabug/images/Campbell --recursive
aws s3 cp Capitola s3://snugabug/images/Capitola --recursive
aws s3 cp Carlsbad s3://snugabug/images/Carlsbad --recursive
aws s3 cp Carmel s3://snugabug/images/Carmel --recursive
aws s3 cp CarmelValley s3://snugabug/images/CarmelValley --recursive
aws s3 cp CastroValley s3://snugabug/images/CastroValley --recursive
aws s3 cp Clayton s3://snugabug/images/Clayton --recursive
aws s3 cp Colma s3://snugabug/images/Colma --recursive
aws s3 cp Concord s3://snugabug/images/Concord --recursive
aws s3 cp CorteMadera s3://snugabug/images/CorteMadera --recursive
aws s3 cp Cotati s3://snugabug/images/Cotati --recursive
aws s3 cp Crockett s3://snugabug/images/Crockett --recursive
aws s3 cp Cupertino s3://snugabug/images/Cupertino --recursive
aws s3 cp DalyCity s3://snugabug/images/DalyCity --recursive
aws s3 cp Danville s3://snugabug/images/Danville --recursive
aws s3 cp Davenport s3://snugabug/images/Davenport --recursive
aws s3 cp Davis s3://snugabug/images/Davis --recursive
aws s3 cp DeerPark s3://snugabug/images/DeerPark --recursive
aws s3 cp Dublin s3://snugabug/images/Dublin --recursive
aws s3 cp EastPaloAlto s3://snugabug/images/EastPaloAlto --recursive
aws s3 cp ElCerrito s3://snugabug/images/ElCerrito --recursive
aws s3 cp Emeryville s3://snugabug/images/Emeryville --recursive
aws s3 cp Encinitas s3://snugabug/images/Encinitas --recursive
aws s3 cp Fairfax s3://snugabug/images/Fairfax --recursive
aws s3 cp Fairfield s3://snugabug/images/Fairfield --recursive
aws s3 cp Felton s3://snugabug/images/Felton --recursive
aws s3 cp Forestville s3://snugabug/images/Forestville --recursive
aws s3 cp FosterCity s3://snugabug/images/FosterCity --recursive
aws s3 cp Fremont s3://snugabug/images/Fremont --recursive
aws s3 cp Geyserville s3://snugabug/images/Geyserville --recursive
aws s3 cp Gilroy s3://snugabug/images/Gilroy --recursive
aws s3 cp GlenEllen s3://snugabug/images/GlenEllen --recursive
aws s3 cp Greenbrae s3://snugabug/images/Greenbrae --recursive
aws s3 cp Groveland s3://snugabug/images/Groveland --recursive
aws s3 cp Guerneville s3://snugabug/images/Guerneville --recursive
aws s3 cp HalfMoonBay s3://snugabug/images/HalfMoonBay --recursive
aws s3 cp Hayward s3://snugabug/images/Hayward --recursive
aws s3 cp Healdsburg s3://snugabug/images/Healdsburg --recursive
aws s3 cp Hillsborough s3://snugabug/images/Hillsborough --recursive
aws s3 cp Kensington s3://snugabug/images/Kensington --recursive
aws s3 cp Kentfield s3://snugabug/images/Kentfield --recursive
aws s3 cp Kenwood s3://snugabug/images/Kenwood --recursive
aws s3 cp Lafayette s3://snugabug/images/Lafayette --recursive
aws s3 cp Larkspur s3://snugabug/images/Larkspur --recursive
aws s3 cp Livermore s3://snugabug/images/Livermore --recursive
aws s3 cp LosAltos s3://snugabug/images/LosAltos --recursive
aws s3 cp LosAltosHills s3://snugabug/images/LosAltosHills --recursive
aws s3 cp LosGatos s3://snugabug/images/LosGatos --recursive
aws s3 cp Martinez s3://snugabug/images/Martinez --recursive
aws s3 cp McClellanPark s3://snugabug/images/McClellanPark --recursive
aws s3 cp MenloPark s3://snugabug/images/MenloPark --recursive
aws s3 cp MillValley s3://snugabug/images/MillValley --recursive
aws s3 cp Millbrae s3://snugabug/images/Millbrae --recursive
aws s3 cp Milpitas s3://snugabug/images/Milpitas --recursive
aws s3 cp Modesto s3://snugabug/images/Modesto --recursive
aws s3 cp Monterey s3://snugabug/images/Monterey --recursive
aws s3 cp Moraga s3://snugabug/images/Moraga --recursive
aws s3 cp MorganHill s3://snugabug/images/MorganHill --recursive
aws s3 cp MorroBay s3://snugabug/images/MorroBay --recursive
aws s3 cp MossBeach s3://snugabug/images/MossBeach --recursive
aws s3 cp MountHamilton s3://snugabug/images/MountHamilton --recursive
aws s3 cp MountainView s3://snugabug/images/MountainView --recursive
aws s3 cp Napa s3://snugabug/images/Napa --recursive
aws s3 cp Needles s3://snugabug/images/Needles --recursive
aws s3 cp Newark s3://snugabug/images/Newark --recursive
aws s3 cp Nicasio s3://snugabug/images/Nicasio --recursive
aws s3 cp Novato s3://snugabug/images/Novato --recursive
aws s3 cp Oakdale s3://snugabug/images/Oakdale --recursive
aws s3 cp Oakland s3://snugabug/images/Oakland --recursive
aws s3 cp Oakley s3://snugabug/images/Oakley --recursive
aws s3 cp Oakville s3://snugabug/images/Oakville --recursive
aws s3 cp Orinda s3://snugabug/images/Orinda --recursive
aws s3 cp Pacifica s3://snugabug/images/Pacifica --recursive
aws s3 cp PaloAlto s3://snugabug/images/PaloAlto --recursive
aws s3 cp Pescadero s3://snugabug/images/Pescadero --recursive
aws s3 cp Petaluma s3://snugabug/images/Petaluma --recursive
aws s3 cp Piedmont s3://snugabug/images/Piedmont --recursive
aws s3 cp Pittsburg s3://snugabug/images/Pittsburg --recursive
aws s3 cp Placerville s3://snugabug/images/Placerville --recursive
aws s3 cp PleasantHill s3://snugabug/images/PleasantHill --recursive
aws s3 cp Pleasanton s3://snugabug/images/Pleasanton --recursive
aws s3 cp PopeValley s3://snugabug/images/PopeValley --recursive
aws s3 cp PortolaValley s3://snugabug/images/PortolaValley --recursive
aws s3 cp RedwoodCity s3://snugabug/images/RedwoodCity --recursive
aws s3 cp Richmond s3://snugabug/images/Richmond --recursive
aws s3 cp Ross s3://snugabug/images/Ross --recursive
aws s3 cp Rutherford s3://snugabug/images/Rutherford --recursive
aws s3 cp Sacramento s3://snugabug/images/Sacramento --recursive
aws s3 cp SaintHelena s3://snugabug/images/SaintHelena --recursive
aws s3 cp Salida s3://snugabug/images/Salida --recursive
aws s3 cp SanAnselmo s3://snugabug/images/SanAnselmo --recursive
aws s3 cp SanBruno s3://snugabug/images/SanBruno --recursive
aws s3 cp SanCarlos s3://snugabug/images/SanCarlos --recursive
aws s3 cp SanFrancisco s3://snugabug/images/SanFrancisco --recursive
aws s3 cp SanJose s3://snugabug/images/SanJose --recursive
aws s3 cp SanLeandro s3://snugabug/images/SanLeandro --recursive
aws s3 cp SanLorenzo s3://snugabug/images/SanLorenzo --recursive
aws s3 cp SanMartin s3://snugabug/images/SanMartin --recursive
aws s3 cp SanMateo s3://snugabug/images/SanMateo --recursive
aws s3 cp SanRafael s3://snugabug/images/SanRafael --recursive
aws s3 cp SanRamon s3://snugabug/images/SanRamon --recursive
aws s3 cp SantaBarbara s3://snugabug/images/SantaBarbara --recursive
aws s3 cp SantaClara s3://snugabug/images/SantaClara --recursive
aws s3 cp SantaCruz s3://snugabug/images/SantaCruz --recursive
aws s3 cp SantaRosa s3://snugabug/images/SantaRosa --recursive
aws s3 cp Saratoga s3://snugabug/images/Saratoga --recursive
aws s3 cp Sausalito s3://snugabug/images/Sausalito --recursive
aws s3 cp ScottsValley s3://snugabug/images/ScottsValley --recursive
aws s3 cp Seaside s3://snugabug/images/Seaside --recursive
aws s3 cp Sebastopol s3://snugabug/images/Sebastopol --recursive
aws s3 cp Sonoma s3://snugabug/images/Sonoma --recursive
aws s3 cp Soquel s3://snugabug/images/Soquel --recursive
aws s3 cp SouthSanFrancisco s3://snugabug/images/SouthSanFrancisco --recursive
aws s3 cp Stanford s3://snugabug/images/Stanford --recursive
aws s3 cp Stockton s3://snugabug/images/Stockton --recursive
aws s3 cp SuisunCity s3://snugabug/images/SuisunCity --recursive
aws s3 cp Sunnyvale s3://snugabug/images/Sunnyvale --recursive
aws s3 cp Sunol s3://snugabug/images/Sunol --recursive
aws s3 cp UnionCity s3://snugabug/images/UnionCity --recursive
aws s3 cp Vacaville s3://snugabug/images/Vacaville --recursive
aws s3 cp Vallejo s3://snugabug/images/Vallejo --recursive
aws s3 cp WalnutCreek s3://snugabug/images/WalnutCreek --recursive
aws s3 cp Waterford s3://snugabug/images/Waterford --recursive
aws s3 cp Watsonville s3://snugabug/images/Watsonville --recursive
aws s3 cp Woodside s3://snugabug/images/Woodside --recursive
aws s3 cp Yountville s3://snugabug/images/Yountville --recursive
