aws s3 rm s3://snugabug/images/Alameda/ --recursive
aws s3 rm s3://snugabug/images/Alamo/ --recursive
aws s3 rm s3://snugabug/images/Albany/ --recursive
aws s3 rm s3://snugabug/images/Antioch/ --recursive
aws s3 rm s3://snugabug/images/Aptos/ --recursive
aws s3 rm s3://snugabug/images/Atherton/ --recursive
aws s3 rm s3://snugabug/images/AvilaBeach/ --recursive
aws s3 rm s3://snugabug/images/Belmont/ --recursive
aws s3 rm s3://snugabug/images/BenLomond/ --recursive
aws s3 rm s3://snugabug/images/Berkeley/ --recursive
aws s3 rm s3://snugabug/images/BoulderCreek/ --recursive
aws s3 rm s3://snugabug/images/Brentwood/ --recursive
aws s3 rm s3://snugabug/images/Brisbane/ --recursive
aws s3 rm s3://snugabug/images/Burlingame/ --recursive
aws s3 rm s3://snugabug/images/Calistoga/ --recursive
aws s3 rm s3://snugabug/images/Campbell/ --recursive
aws s3 rm s3://snugabug/images/Capitola/ --recursive
aws s3 rm s3://snugabug/images/Carlsbad/ --recursive
aws s3 rm s3://snugabug/images/Carmel/ --recursive
aws s3 rm s3://snugabug/images/CarmelValley/ --recursive
aws s3 rm s3://snugabug/images/CastroValley/ --recursive
aws s3 rm s3://snugabug/images/Clayton/ --recursive
aws s3 rm s3://snugabug/images/Colma/ --recursive
aws s3 rm s3://snugabug/images/Concord/ --recursive
aws s3 rm s3://snugabug/images/CorteMadera/ --recursive
aws s3 rm s3://snugabug/images/Cotati/ --recursive
aws s3 rm s3://snugabug/images/Cupertino/ --recursive
aws s3 rm s3://snugabug/images/DalyCity/ --recursive
aws s3 rm s3://snugabug/images/Danville/ --recursive
aws s3 rm s3://snugabug/images/Davenport/ --recursive
aws s3 rm s3://snugabug/images/Davis/ --recursive
aws s3 rm s3://snugabug/images/DeerPark/ --recursive
aws s3 rm s3://snugabug/images/Dublin/ --recursive
aws s3 rm s3://snugabug/images/ElCerrito/ --recursive
aws s3 rm s3://snugabug/images/Emeryville/ --recursive
aws s3 rm s3://snugabug/images/Encinitas/ --recursive
aws s3 rm s3://snugabug/images/Fairfax/ --recursive
aws s3 rm s3://snugabug/images/Fairfield/ --recursive
aws s3 rm s3://snugabug/images/Felton/ --recursive
aws s3 rm s3://snugabug/images/Forestville/ --recursive
aws s3 rm s3://snugabug/images/FosterCity/ --recursive
aws s3 rm s3://snugabug/images/Fremont/ --recursive
aws s3 rm s3://snugabug/images/Geyserville/ --recursive
aws s3 rm s3://snugabug/images/Gilroy/ --recursive
aws s3 rm s3://snugabug/images/GlenEllen/ --recursive
aws s3 rm s3://snugabug/images/Greenbrae/ --recursive
aws s3 rm s3://snugabug/images/Groveland/ --recursive
aws s3 rm s3://snugabug/images/Guerneville/ --recursive
aws s3 rm s3://snugabug/images/HalfMoonBay/ --recursive
aws s3 rm s3://snugabug/images/Hayward/ --recursive
aws s3 rm s3://snugabug/images/Healdsburg/ --recursive
aws s3 rm s3://snugabug/images/Hillsborough/ --recursive
aws s3 rm s3://snugabug/images/Kensington/ --recursive
aws s3 rm s3://snugabug/images/Kentfield/ --recursive
aws s3 rm s3://snugabug/images/Kenwood/ --recursive
aws s3 rm s3://snugabug/images/Lafayette/ --recursive
aws s3 rm s3://snugabug/images/Larkspur/ --recursive
aws s3 rm s3://snugabug/images/Livermore/ --recursive
aws s3 rm s3://snugabug/images/LosAltos/ --recursive
aws s3 rm s3://snugabug/images/LosAltosHills/ --recursive
aws s3 rm s3://snugabug/images/LosGatos/ --recursive
aws s3 rm s3://snugabug/images/Marin/ --recursive
aws s3 rm s3://snugabug/images/Martinez/ --recursive
aws s3 rm s3://snugabug/images/McClellanPark/ --recursive
aws s3 rm s3://snugabug/images/MenloPark/ --recursive
aws s3 rm s3://snugabug/images/MillValley/ --recursive
aws s3 rm s3://snugabug/images/Millbrae/ --recursive
aws s3 rm s3://snugabug/images/Milpitas/ --recursive
aws s3 rm s3://snugabug/images/Modesto/ --recursive
aws s3 rm s3://snugabug/images/Monterey/ --recursive
aws s3 rm s3://snugabug/images/Moraga/ --recursive
aws s3 rm s3://snugabug/images/MorganHill/ --recursive
aws s3 rm s3://snugabug/images/MorroBay/ --recursive
aws s3 rm s3://snugabug/images/MossBeach/ --recursive
aws s3 rm s3://snugabug/images/MountHamilton/ --recursive
aws s3 rm s3://snugabug/images/MountainView/ --recursive
aws s3 rm s3://snugabug/images/Napa/ --recursive
aws s3 rm s3://snugabug/images/Needles/ --recursive
aws s3 rm s3://snugabug/images/Newark/ --recursive
aws s3 rm s3://snugabug/images/Nicasio/ --recursive
aws s3 rm s3://snugabug/images/Novato/ --recursive
aws s3 rm s3://snugabug/images/Oakdale/ --recursive
aws s3 rm s3://snugabug/images/Oakland/ --recursive
aws s3 rm s3://snugabug/images/Oakley/ --recursive
aws s3 rm s3://snugabug/images/Oakville/ --recursive
aws s3 rm s3://snugabug/images/Orinda/ --recursive
aws s3 rm s3://snugabug/images/Pacifica/ --recursive
aws s3 rm s3://snugabug/images/PaloAlto/ --recursive
aws s3 rm s3://snugabug/images/Pescadero/ --recursive
aws s3 rm s3://snugabug/images/Petaluma/ --recursive
aws s3 rm s3://snugabug/images/Piedmont/ --recursive
aws s3 rm s3://snugabug/images/Pittsburg/ --recursive
aws s3 rm s3://snugabug/images/Placerville/ --recursive
aws s3 rm s3://snugabug/images/PleasantHill/ --recursive
aws s3 rm s3://snugabug/images/Pleasanton/ --recursive
aws s3 rm s3://snugabug/images/PointRichmond/ --recursive
aws s3 rm s3://snugabug/images/PopeValley/ --recursive
aws s3 rm s3://snugabug/images/PortolaValley/ --recursive
aws s3 rm s3://snugabug/images/RedwoodCity/ --recursive
aws s3 rm s3://snugabug/images/Richmond/ --recursive
aws s3 rm s3://snugabug/images/Ross/ --recursive
aws s3 rm s3://snugabug/images/RossValley/ --recursive
aws s3 rm s3://snugabug/images/Rutherford/ --recursive
aws s3 rm s3://snugabug/images/Sacramento/ --recursive
aws s3 rm s3://snugabug/images/SaintHelena/ --recursive
aws s3 rm s3://snugabug/images/Salida/ --recursive
aws s3 rm s3://snugabug/images/SanAnselmo/ --recursive
aws s3 rm s3://snugabug/images/SanBruno/ --recursive
aws s3 rm s3://snugabug/images/SanCarlos/ --recursive
aws s3 rm s3://snugabug/images/SanFrancisco/ --recursive
aws s3 rm s3://snugabug/images/SanJose/ --recursive
aws s3 rm s3://snugabug/images/SanLeandro/ --recursive
aws s3 rm s3://snugabug/images/SanLorenzo/ --recursive
aws s3 rm s3://snugabug/images/SanMartin/ --recursive
aws s3 rm s3://snugabug/images/SanMateo/ --recursive
aws s3 rm s3://snugabug/images/SanRafael/ --recursive
aws s3 rm s3://snugabug/images/SanRamon/ --recursive
aws s3 rm s3://snugabug/images/SantaBarbara/ --recursive
aws s3 rm s3://snugabug/images/SantaClara/ --recursive
aws s3 rm s3://snugabug/images/SantaCruz/ --recursive
aws s3 rm s3://snugabug/images/SantaRosa/ --recursive
aws s3 rm s3://snugabug/images/Saratoga/ --recursive
aws s3 rm s3://snugabug/images/Sausalito/ --recursive
aws s3 rm s3://snugabug/images/ScottsValley/ --recursive
aws s3 rm s3://snugabug/images/Seaside/ --recursive
aws s3 rm s3://snugabug/images/Sebastopol/ --recursive
aws s3 rm s3://snugabug/images/Sonoma/ --recursive
aws s3 rm s3://snugabug/images/Soquel/ --recursive
aws s3 rm s3://snugabug/images/SouthSanFrancisco/ --recursive
aws s3 rm s3://snugabug/images/Stanford/ --recursive
aws s3 rm s3://snugabug/images/Stockton/ --recursive
aws s3 rm s3://snugabug/images/SuisunCity/ --recursive
aws s3 rm s3://snugabug/images/Sunnyvale/ --recursive
aws s3 rm s3://snugabug/images/Sunol/ --recursive
aws s3 rm s3://snugabug/images/UnionCity/ --recursive
aws s3 rm s3://snugabug/images/Vacaville/ --recursive
aws s3 rm s3://snugabug/images/Vallejo/ --recursive
aws s3 rm s3://snugabug/images/WalnutCreek/ --recursive
aws s3 rm s3://snugabug/images/Waterford/ --recursive
aws s3 rm s3://snugabug/images/Watsonville/ --recursive
aws s3 rm s3://snugabug/images/Woodside/ --recursive
aws s3 rm s3://snugabug/images/Yountville/ --recursive
